### ISSUE TITLE
jlogstash可以在k8s容器中运行吗？尝试过做成镜像在k8s上运行，遇到报Java heap space，但非容器正常。如果容器化部署，有相关的部署说明吗？谢谢

### ISSUE THREAD

**Issue by zt520374** [DTStack/jlogstash#36]
2019-07-02 13:44:10.619 [main] INFO  org.elasticsearch.plugins.PluginsService [PluginsService.java:180] - loaded plugin [org.elasticsearch.transport.Netty4Plugin]
java.lang.OutOfMemoryError: Java heap space
Dumping heap to ../logs/heapdump.hprof ...
Heap dump file created [380426013 bytes in 2.713 secs]
Exception in thread "elasticsearch[_client_][scheduler][T#1]" java.lang.OutOfMemoryError: Java heap space
Exception in thread "elasticsearch[_client_][scheduler][T#1]" java.lang.IllegalMonitorStateException
2019-07-02 13:45:13.213 [elasticsearch[_client_][transport_client_boss][T#5]] WARN  io.netty.util.ReferenceCountUtil [Netty4InternalESLogger.java:149] - Failed to release a message: PooledDirectByteBuf(freed)
java.lang.OutOfMemoryError: Java heap space
at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.signal(AbstractQueuedSynchronizer.java:1939)
at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1103)
at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "elasticsearch[_client_][generic][T#1]"

**Comment by yangsishu** [comment]
容器化部署没试过，你这个在docker部署的时候内存分配稍微给大些

**Comment by zt520374** [comment]
恩，测试过，HO_HEAP_SIZE设置500m时候，启动时报Java heap space。目前已经设置HO_HEAP_SIZE=1024m，启动不报错，也可以正常读取kafka数据，输出到ES，但使用内存在缓慢增加中，正在监控中，看看后续还有啥异常
